name: login_template
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  formz: ^0.8.0
  equatable: ^2.0.8
  intl: ^0.20.2
  dio: ^5.9.2
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^10.0.0
  logger: ^2.7.0
  circular_bottom_navigation: ^2.4.0
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
